In [2]:
!pip install textblob
from textblob import TextBlob
import pandas as pd

Requirement already satisfied: textblob in /Users/sushilpandey/Desktop/python-learning/pyLibraries/lib/python3.13/site-packages (0.20.0)
Requirement already satisfied: nltk>=3.9 in /Users/sushilpandey/Desktop/python-learning/pyLibraries/lib/python3.13/site-packages (from textblob) (3.9.4)
Requirement already satisfied: click in /Users/sushilpandey/Desktop/python-learning/pyLibraries/lib/python3.13/site-packages (from nltk>=3.9->textblob) (8.3.3)
Requirement already satisfied: joblib in /Users/sushilpandey/Desktop/python-learning/pyLibraries/lib/python3.13/site-packages (from nltk>=3.9->textblob) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /Users/sushilpandey/Desktop/python-learning/pyLibraries/lib/python3.13/site-packages (from nltk>=3.9->textblob) (2026.4.4)
Requirement already satisfied: tqdm in /Users/sushilpandey/Desktop/python-learning/pyLibraries/lib/python3.13/site-packages (from nltk>=3.9->textblob) (4.67.3)

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [3]:
# Load dataset
df = pd.read_csv("./swiggydataset.csv")
print(df)

                   date  favorite_count  followers_count  friends_count  \
0       7/18/2019 22:47               0               82            219
1       7/18/2019 22:43               0              102            129
2       7/18/2019 22:37               0              102            129
3       7/18/2019 22:35               0               13             16
4       7/18/2019 22:25               0              102            129
...                 ...             ...              ...            ...
16707  07-11-2019 12:13               0                0              2
16708  07-11-2019 12:12               0              106            146
16709  07-11-2019 12:11               0               91            248
16710  07-11-2019 12:11               0                0              2
16711  07-11-2019 12:09               0               54            163

                                               full_text  retweet_count  \
0      @Mahi_2510 @swiggy_in The ultimate answer will...              0
1                                @SwiggyCares I hope so.              0
2      @SwiggyCares I think you have the order detail...              0
3      @swiggy_in People are complaining here also, i...              0
4      @SwiggyCares Do you even know the meaning of y...              0
...                                                  ...            ...
16707  @SwiggyCares they said as delivery box is not ...              0
16708  @swiggy_in Deliver to karta nahi, install kyo ...              0
16709  @swiggy_in thanks for spilling my drink. I wai...              0
16710  @SwiggyCares hello there i use swigggy regular...              0
16711  @Being_Humor @ZomatoIN @swiggy_in can you help...              0

      retweeted      screen_name tweet_id                      user_id
0         False       syamantak1        1                  6,19,59,419
1         False    Bharatbbhushn        2                 14,32,84,383
2         False    Bharatbbhushn        3                 14,32,84,383
3         False     taifkhalid01        4   8,30,34,00,00,00,00,00,000
4         False    Bharatbbhushn        5                 14,32,84,383
...         ...              ...      ...                          ...
16707     False   UmmeMohammad18   16,708  11,44,99,00,00,00,00,00,000
16708     False       Desi_Life1   16,709  10,39,41,00,00,00,00,00,000
16709     False   Pinks_Forever_   16,710               1,70,09,14,573
16710     False   UmmeMohammad18   16,711  11,44,99,00,00,00,00,00,000
16711     False  TejasShelar2498   16,712   7,17,51,10,00,00,00,00,000

[16712 rows x 10 columns]

In [4]:
# Take only text column
df = df[['full_text']].dropna()

In [5]:
# Function to get sentiment
def get_sentiment(text):
    score = TextBlob(text).sentiment.polarity
    
    if score > 0:
        return "Positive"
    elif score < 0:
        return "Negative"
    else:
        return "Neutral"

In [6]:
# Apply sentiment
df['sentiment'] = df['full_text'].apply(get_sentiment)

In [4]:
# Show results
df.head()

,date,favorite_count,followers_count,friends_count,full_text,retweet_count,retweeted,screen_name,tweet_id,user_id
0,7/18/2019 22:47,0,82,219,@Mahi_2510 @swiggy_in The ultimate answer will...,0,False,syamantak1,1,"6,19,59,419"
1,7/18/2019 22:43,0,102,129,@SwiggyCares I hope so.,0,False,Bharatbbhushn,2,"14,32,84,383"
2,7/18/2019 22:37,0,102,129,@SwiggyCares I think you have the order detail...,0,False,Bharatbbhushn,3,"14,32,84,383"
3,7/18/2019 22:35,0,13,16,"@swiggy_in People are complaining here also, i...",0,False,taifkhalid01,4,"8,30,34,00,00,00,00,00,000"
4,7/18/2019 22:25,0,102,129,@SwiggyCares Do you even know the meaning of y...,0,False,Bharatbbhushn,5,"14,32,84,383"

In [8]:
# Count results
print("\nSentiment Count:\n")
print(df['sentiment'].value_counts())

Sentiment Count:

sentiment
Neutral     5790
Negative    5463
Positive    5459
Name: count, dtype: int64

In [ ]:
#practice code

from textblob import TextBlob
import pandas as pd

In [10]:
df = pd.read_csv('./swiggydataset.csv')

In [11]:
df.head()

,date,favorite_count,followers_count,friends_count,full_text,retweet_count,retweeted,screen_name,tweet_id,user_id
0,7/18/2019 22:47,0,82,219,@Mahi_2510 @swiggy_in The ultimate answer will...,0,False,syamantak1,1,"6,19,59,419"
1,7/18/2019 22:43,0,102,129,@SwiggyCares I hope so.,0,False,Bharatbbhushn,2,"14,32,84,383"
2,7/18/2019 22:37,0,102,129,@SwiggyCares I think you have the order detail...,0,False,Bharatbbhushn,3,"14,32,84,383"
3,7/18/2019 22:35,0,13,16,"@swiggy_in People are complaining here also, i...",0,False,taifkhalid01,4,"8,30,34,00,00,00,00,00,000"
4,7/18/2019 22:25,0,102,129,@SwiggyCares Do you even know the meaning of y...,0,False,Bharatbbhushn,5,"14,32,84,383"

In [12]:
df = df[["full_text"]]

In [13]:
df

                                               full_text
0      @Mahi_2510 @swiggy_in The ultimate answer will...
1                                @SwiggyCares I hope so.
2      @SwiggyCares I think you have the order detail...
3      @swiggy_in People are complaining here also, i...
4      @SwiggyCares Do you even know the meaning of y...
...                                                  ...
16707  @SwiggyCares they said as delivery box is not ...
16708  @swiggy_in Deliver to karta nahi, install kyo ...
16709  @swiggy_in thanks for spilling my drink. I wai...
16710  @SwiggyCares hello there i use swigggy regular...
16711  @Being_Humor @ZomatoIN @swiggy_in can you help...

[16712 rows x 1 columns]

In [14]:
def senti_anal(txt):
    score = TextBlob(txt).sentiment.polarity

    if score > 0:
        return "positive sentence"
    elif score < 0:
        return "negative sentence"
    else:
        return "neutral sentence"

In [15]:
df["sentence_sentiment"] = df["full_text"].apply(senti_anal)

In [16]:
df.head()

                                           full_text sentence_sentiment
0  @Mahi_2510 @swiggy_in The ultimate answer will...  negative sentence
1                            @SwiggyCares I hope so.   neutral sentence
2  @SwiggyCares I think you have the order detail...  positive sentence
3  @swiggy_in People are complaining here also, i...  positive sentence
4  @SwiggyCares Do you even know the meaning of y...   neutral sentence

In [18]:
print("sentimental analysis")
print(df["sentence_sentiment"].value_counts())

sentimental analysis
sentence_sentiment
neutral sentence     5790
negative sentence    5463
positive sentence    5459
Name: count, dtype: int64